language: ruby
script: "bundle exec rake travis:ci"
rvm:
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0
gemfile:
  - gemfiles/cucumber.1.3.gemfile
  - gemfiles/cucumber.2.4.gemfile
  - gemfiles/latest.gemfile
  - gemfiles/rspec.3.0.gemfile
  - gemfiles/spinach.0.8.gemfile
